In [25]:
import pandas as pd
import requests
from io import StringIO

url = "https://raw.githubusercontent.com/kavya-prabahar/Personalized-learning-system/main/learning_style_dataset.csv"

response = requests.get(url)
if response.status_code == 200:
    data = StringIO(response.text)
    dataset = pd.read_csv(data)
    print(dataset.head())
else:
    print("Failed to download the dataset")


   quiz_score  time_spent learning_style
0          51          53       auditory
1          92          44         visual
2          14          20    kinesthetic
3          71          52         visual
4          60          32       auditory


In [31]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, recall_score, precision_score, f1_score

x = dataset[['quiz_score', 'time_spent']]
y = dataset['learning_style']

X_train, X_test, Y_train, Y_test = train_test_split(x, y, random_state=0, train_size=0.75)

clf = KNeighborsClassifier(n_neighbors=3)

clf.fit(X_train, Y_train)

Y_pred = clf.predict(X_test)

cm = confusion_matrix(Y_test, Y_pred)
print("Confusion Matrix:")
print(cm)

ac = accuracy_score(Y_test, Y_pred)
print(f"Accuracy: {ac}")

precision = precision_score(Y_test, Y_pred, average="micro")
print(f"Precision: {precision}")

recall = recall_score(Y_test, Y_pred, average="micro")
print(f"Recall: {recall}")

f1 = f1_score(Y_test, Y_pred, average="micro")
print(f"F1 Score: {f1}")

cv_scores = cross_val_score(clf, x, y, cv=5)
print(f"Cross-Validation Scores: {cv_scores}")
print(f"Mean Cross-Validation Score: {np.mean(cv_scores)}")


Confusion Matrix:
[[3729    0    0]
 [   0 4953    0]
 [   0    0 3818]]
Accuracy: 1.0
Precision: 1.0
Recall: 1.0
F1 Score: 1.0
Cross-Validation Scores: [0.9999 1.     0.9999 1.     1.    ]
Mean Cross-Validation Score: 0.9999600000000001
